import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ChakraProvider, Container, defaultSystem } from "@chakra-ui/react";
import { Provider } from "@/components/ui/provider";
import Header from "@/components/header/header";

const roboto = Roboto();

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.className} antialiased`}>
				<Provider>
					<Header />
					<Container>{children}</Container>
				</Provider>
			</body>
		</html>
	);
}
