export const categories = [
	{ text: "Фантастика", value: "science fiction", popular: true },
	{ text: "Фэнтези", value: "fantasy", popular: true },
	{ text: "Романы", value: "fiction", popular: true },
	{ text: "Детективы", value: "mystery", popular: true },
	{ text: "Триллеры", value: "thriller" },
	{ text: "Ужасы", value: "horror", popular: true },
	{ text: "Романтика", value: "romance", popular: true },
	{ text: "Биографии", value: "biography" },
	{ text: "История", value: "history" },
	{ text: "Наука", value: "science" },
	{ text: "Технологии", value: "technology", popular: true },
	{ text: "Программирование", value: "computer programming", popular: true },
	{ text: "Бизнес", value: "business" },
	{ text: "Финансы", value: "finance" },
	{ text: "Психология", value: "psychology", popular: true },
	{ text: "Саморазвитие", value: "self-help", popular: true },
	{ text: "Здоровье", value: "health" },
	{ text: "Кулинария", value: "cooking" },
	{ text: "Путешествия", value: "travel" },
	{ text: "Искусство", value: "art" },
	{ text: "Музыка", value: "music" },
	{ text: "Поэзия", value: "poetry" },
	{ text: "Детские книги", value: "juvenile fiction", popular: true },
	{ text: "Комиксы", value: "comics" },
	{ text: "Философия", value: "philosophy" },
	{ text: "Религия", value: "religion" },
	{ text: "Спорт", value: "sports" },
	{ text: "Юмор", value: "humor" },
	{ text: "Юридическая литература", value: "law" },
	{ text: "Медицина", value: "medical" },
];
